//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinFormsDesktopQuiz
{
    using System;
    using System.Collections.Generic;
    
    public partial class Score
    {
        public int ScoreId { get; set; }
        public string CallSign { get; set; }
        public int CorrectAnswerCount { get; set; }
    }
}
